Adding endpoints
hmrc/individuals-if-api-stub pull request #5
Opened 2020-10-19 14:02 UTC by parkeradam

2020-10-19 14:28 UTC, matthewharris1 requested changes
Looks good just some whitespace that needs removed

2020-10-19 14:28 UTC, matthewharris1 commented on app/uk/gov/hmrc/individualsifapistub/domain/JsonFormatters.scala
> +
Random white space?

2020-10-19 14:50 UTC, owen-opencast commented on app/uk/gov/hmrc/individualsifapistub/repository/IncomeRepository.scala
> +  extends ReactiveRepository[Income, BSONObjectID]( "Income",
Key is lower-case in the other repositories

2020-10-21 12:29 UTC, matthewharris1 approved these changes

2020-10-21 13:13 UTC, merged