Add JSON stubs for LAA C1 to C4
hmrc/individuals-if-api-stub pull request #8
Opened 2020-10-30 12:43 UTC by ajchilts

2020-11-02 11:54 UTC, parkeradam commented on conf/resouces/stubs-json-payloads/income/LAA/C4/SA-single-tax-year-single-return-list.json
> +            "busStartDate": "2018-02-28",
busStartDate and busEndDate not needed for C4 This will need to be actioned on all LAA C4 SA payloads

2020-11-02 14:20 UTC, parkeradam approved these changes

2020-11-02 17:59 UTC, Bongowhack requested changes
LAA/C4/SA-multi-tax-year-multi-return-list.json
LAA/C4/SA-single-tax-year-multi-return-list.json

Both of the above files have additional/unwanted fields in them

2020-11-02 17:59 UTC, Bongowhack commented on conf/resouces/stubs-json-payloads/income/LAA/C4/SA-multi-tax-year-multi-return-list.json
> +            "tradingIncomeAllowance": 100,
Remove additional fields.

2020-11-02 17:59 UTC, Bongowhack commented on conf/resouces/stubs-json-payloads/income/LAA/C4/SA-multi-tax-year-multi-return-list.json
> +            "tradingIncomeAllowance": 900,
Remove additional fields

2020-11-02 17:59 UTC, Bongowhack commented on conf/resouces/stubs-json-payloads/income/LAA/C4/SA-multi-tax-year-multi-return-list.json
> +            "tradingIncomeAllowance": 100
Remove additional fields.

2020-11-02 17:59 UTC, Bongowhack commented on conf/resouces/stubs-json-payloads/income/LAA/C4/SA-multi-tax-year-multi-return-list.json
> +            "tradingIncomeAllowance": 900
Remove additional fields.

2020-11-02 17:59 UTC, Bongowhack commented on conf/resouces/stubs-json-payloads/income/LAA/C4/SA-single-tax-year-multi-return-list.json
> +            "tradingIncomeAllowance": 100
Remove additional fields.

2020-11-02 17:59 UTC, Bongowhack commented on conf/resouces/stubs-json-payloads/income/LAA/C4/SA-single-tax-year-multi-return-list.json
> +            "tradingIncomeAllowance": 900
Remove additional fields.

2020-11-03 10:23 UTC, Bongowhack approved these changes
Sorted

2020-11-04 13:35 UTC, merged